name: Trigger auto deployment for worker-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/worker-service-AutoDeployTrigger-25065ae2-d14b-44bd-91be-6bfd01f0c725.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.WORKERSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WORKERSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WORKERSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: distcronregistry.azurecr.io
          registryUsername: ${{ secrets.WORKERSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WORKERSERVICE_REGISTRY_PASSWORD }}
          containerAppName: worker-service
          resourceGroup: distributed-cron-rg
          imageToBuild: distcronregistry.azurecr.io/worker-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


